################
### Language ###
################
language: java

###########
### JDK ###
###########
jdk:
  - oraclejdk11

#####################
### Notifications ###
#####################
notifications:
  email: false

####################
### Build script ###
####################
script:
  - mvn clean compile
  - mvn verify sonar:sonar -Dsonar.host.url=https://sonar.klauke-enterprises.com -Dsonar.projectKey=luna -Dsonar.login=$SONAR_TOKEN

##################
### Deployment ###
##################
deploy:
  provider: script
  script: mvn deploy --settings deploy/maven-settings.xml
  on:
    branch: master
    tags: true

env:
  global:
    - secure: BKqYO9VqYgSv/GIBufNhu0R6TJvtF9AyFlbieL2JqNjGBM9KhhibBTonl5sKHgJpdoUdhwG/87EkH4Ogd0WAfZL07HVo64yNuXtZqSMsaq5JUUknK7IcuDGD3y/rWKpyhKuA1H5fQkoxnETEvnmmUtL0JKOy4059DpMYrtKNpspHazT9keak86ZeiAnYbBN7imHeCFayh1mTVGvwlV5+ggplp97PcislmQlxMo2Z0AkOAi1etQwI4q+TRIyO8rEDDrnmRm4nBCehqesj8Db45Ks6mUp/ZUkSGXFSOYm89rpNsYZGiIoJTV7hRtMr0QaGM7INCKlIFISNt1nj6aGXLEy1EZM7YxaXOWr3U9HTCkK8cvo4mOfiTI0Sn+oUsKivVzlXutD9hhqSDDH1ireq8lAAhuCh8VwmRzamm3r0gXL0giHf1ONEPw8rKs9tT5F7CLc/fpb+YG4URYHr48Abe0fwaHKiJsL8/dBLLcyTXAaNimvXLuZ3aW86UXVWwZzKj8hZG5BjqarOCf0ejJ+LuD6lkAaZY0wPjxPJme/EPG+sjTQASQRgOiX2AUUfpL7Y7DJB5Y1L7BAvtyiE4rQBfFaHdXGdDCRIWWp1aOT7CC3EeKd02bzGMvay7LLRUbknJcIFUijppprhvGeSIr6wECjQTkOt7k0B4iVAeYzNyC0=
    - secure: aeiL3BINdeGNjuxEaYWAWZ3DJCDTkZF0Wr/JY5XROU2TsUe2z29V/hMIIBGMuptz6SCsLv4vlvlIIBYyRngbGBHNS4Z2mKNkQwpv4+OPT7hiX5gwOMoVJhBF3FYda5g9DO/TFCPIMqFSaBuwrMSp0LpwAkEDPzW+5uDxyNnSxdh4JwhER+5niIKK00/NAOFGjvZzvrV/r7tJ5zNcFnKSw567CZ8tZn2lpsb8JwSGXAPSOIMgzHxtvHjo0P6U7AX0JHvqd8qKVCZRZ17vcVCEs80CM7NE2E0Z9Wq86eQEcaFZ6YljQoOV03QEEJHaNuOGuZJuVyZ0dgPPOw64o6JyxxZylhnh6Y58GW+fzlhHTH/wKXCWjZyrszmyZgDVZD7/UXgklQyww1+mUB+42OwWkIOfY+br+7fxUKBW+SmHKul486WXYBJBB70gcPvrzEWIitRczpOG7qjw0Ll99+m8nhZCoUiSlA+QpLtT7eoO0N66Af6AAFYXrSbc2MY6p5mYc09DIuz/wdiLFEfJkPKvOMkmdCME5wo0g9DfHyoGvvcWImCWIWXOyarwtYg2r22Bkl6CsAytxNHu0pqx52eaXCFhAngyLRk+p6ndLKFYbcRG1L6KXbemjY97QfqC2qchQnjf6e+dQ2qGkykeU/t9vafF/WmWwVYj2o0g7M8NTGU=
    - secure: y2tvwPYxNWFTv2BMMLKkckc62Q0kxVwMeQCOezVLaxdOXFTBQrjmg6mr4xFapFuWQEpqjRaPXAunQuDzyuAr4rucRR9o1ZexuItYC2ft3Yduk6YzYFfTlYo5k4HWm4HzWMFmetzI3PemL0JN41p2IKnRqVx+EtxCCvkSV69iZDJv3CHvKwztGUhZas+pBaFJ9UzqA8lI9az5ORA3dxVEnsFBmNS0H6xHIJzMJCzRn7cDxHliTei3NMCsie36JEejA9/FHSwKhT/HvbGInKc8ZLtH6jAprA5ftHW/MW2AILCBEwWqzgQ20jr1EiRTnib7bz63x428ukkiAbfUQ0NEVzlV/AMD0CwGSTTFDkrsVCL3u7a7Qx5LYdiZOoZqkI/dMhPV5NQUtRPnXuaoRqLGGj0ULsNd4LXyb6RLDXLG+d9QjQ1dOtan1MD+MrHR93F+7folP1GG0IgbUJXpnbS3l14aIgxDcADEdl+FHXje6vv1pAirqhRIZo/PkGN59jIn3aVxmUbnaIsKfWlI85MtGPzJw0Os7fVqIoFJuZYw7DNlj5YhpkEdSKCZYIkxXeRVjRg/qYKaQ27TdrdCdjt1fh7RzFxox/PMxN0lHHzK3vuv95LWoUKr0vQfaaqcfAkbvYLb9UTcedzCkm8A2SODN1HGwyB95dTwjVDNkhnsjkE=
